# Regression with Keras

### Predict Global Sales

In [31]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score, KFold

import tensorflow.keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.wrappers.scikit_learn import KerasRegressor

### LOADING DATASET

In [2]:
df = pd.read_csv('data/games_out.csv')
df

,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,Platform_0,Platform_1,Platform_2,Platform_3,Platform_4,...,Publisher_577,Publisher_578,Rating_0,Rating_1,Rating_2,Rating_3,Rating_4,Rating_5,Rating_6,Rating_7
0,41.36,28.96,3.77,8.45,82.53,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
1,29.08,3.58,6.81,0.77,40.24,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
2,15.68,12.76,3.79,3.29,35.52,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,15.61,10.93,3.28,2.95,32.77,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
4,11.27,8.89,10.22,1.00,31.37,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16660,0.00,0.00,0.01,0.00,0.01,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
16661,0.00,0.01,0.00,0.00,0.01,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
16662,0.00,0.00,0.01,0.00,0.01,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0
16663,0.01,0.00,0.00,0.00,0.01,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
16664,0.00,0.00,0.01,0.00,0.01,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

## Creating Arrays for the Features and the Response Variable

In [3]:
X = df.iloc[:, 5:].values
y = df['Global_Sales'].values

## Creating the train and test datasets

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
print('X_train.shape=', X_train.shape, '/ X_test.shape=', X_test.shape)

X_train.shape= (11665, 628) / X_test.shape= (5000, 628)

## Building the Deep Learning Regression Model

In [25]:
def baseline_model():
    input_shape = len(X[0])
    units = round(input_shape / 2)
    
    model = Sequential()
    model.add(Dense(units=units, input_shape=(input_shape,), activation='relu'))
    model.add(Dense(units=units, activation='relu'))
    model.add(Dense(units=1, activation='relu'))
    
    # Compile model
    model.compile(loss='mean_squared_error', optimizer='adam')
    
    return model

## Evaluate model

#### Number of inputs

In [26]:
input_shape = len(X[0])
units = round(input_shape / 2)
print('input_shape=', input_shape, "/ units=", units)

input_shape= 628 / units= 314

In [34]:
estimator = KerasRegressor(build_fn=baseline_model, epochs=10, batch_size=5, verbose=0)
kfold = KFold(n_splits=10)
results = cross_val_score(estimator, X, y, cv=kfold, scoring='neg_mean_squared_error')

/tmp/ipykernel_9633/1116579642.py:1: DeprecationWarning: KerasRegressor is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  estimator = KerasRegressor(build_fn=baseline_model, epochs=10, batch_size=5, verbose=0)

NameError: name 'results' is not defined

In [35]:
print("Baseline: %.2f (%.2f) MSE" % (result.mean(), result.std()))

Baseline: -2.63 (6.80) MSE